# Generated by Django 5.0.7 on 2024-07-19 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_resource"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="date_reported",
            new_name="date_uploaded",
        ),
    ]
