# Generated by Django 5.0.7 on 2024-07-19 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_date_reported_incident_date_uploaded"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Incident",
        ),
    ]
