# Generated by Django 5.0.7 on 2024-07-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_resource_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("MATH 31.1", "MATH 31.1"),
                            ("LAS 21", "LAS 21"),
                            ("MATH 31.2", "MATH 31.2"),
                            ("DECSC 22", "DECSC 22"),
                            ("ITMGT 25.03", "ITMGT 25.03"),
                            ("MATH 31.3", "MATH 31.3"),
                            ("ACCT 115", "ACCT 115"),
                            ("LLAW 113", "LLAW 113"),
                            ("MATH 70.1", "MATH 70.1"),
                            ("ECON 110", "ECON 110"),
                            ("ACCT 125", "ACCT 125"),
                            ("LLAW 115", "LLAW 115"),
                            ("MATH 61.2", "MATH 61.2"),
                            ("DECSC 25", "DECSC 25"),
                            ("ECON 121", "ECON 121"),
                            ("FINN 115", "FINN 115"),
                            ("QUANT 121", "QUANT 121"),
                            ("QUANT 162", "QUANT 162"),
                            ("LAS 111", "LAS 111"),
                            ("MKTG 111", "MKTG 111"),
                            ("QUANT 163", "QUANT 163"),
                            ("LAS 123", "LAS 123"),
                            ("QUANT 192", "QUANT 192"),
                            ("LAS 120", "LAS 120"),
                            ("LAS 140", "LAS 140"),
                            ("OPMAN 125", "OPMAN 125"),
                            ("QUANT 164", "QUANT 164"),
                            ("QUANT 199", "QUANT 199"),
                            ("LAS 197.10", "LAS 197.10"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="resource",
            name="subject",
        ),
        migrations.AddField(
            model_name="resource",
            name="subjects",
            field=models.ManyToManyField(to="blog.subject"),
        ),
    ]
